### ISSUE TITLE
Изменение внешнего вида постов в Ленте

### ISSUE THREAD

**Issue by AndreyKondakovGW** [AndreyKondakovGW/Project-Sbornik-Pervokursnika-#12]
добавить под постом информацию о времени его публикации (есть в классе поста), также подумать о расположении аватара сообщества/пользователя опубликовавшего этот пост(для начала можно просто  грузить одну и туже картинку для всех постов, пока на бэке не сделают запоминание автора поста)

**Comment by Ekaterina0801** [comment]
Готово
