### ISSUE TITLE
Изменение внешнего вида страницы "Профиль"

### ISSUE THREAD

**Issue by AndreyKondakovGW** [AndreyKondakovGW/Project-Sbornik-Pervokursnika-#14]
1)Убрать кнопки смены темы, заменить на список с выбором одного из вариантов как на картинке (1)
2)Добавить раздел с настройкой пуш уведомлений состоящий из 2 переключателей: "получать уведомления по тэгам ленты" и "получать уведомления только по особо важным постам". Также поместить туда кнопку меню тэгов сменить её название на: "Настройка уведомлений по тэгам в ленте"
3) Добавить подписи к разделам в Профиле (1)Смена темы 2)Настройка Пуш уведомлений)
![s5mgplTeAvQ](https://user-images.githubusercontent.com/54818412/125739199-9631bcd2-1392-49ee-bd63-b0edbcbfbc3d.jpg)

**Comment by DmitryiShvets** [comment]
Исправлено. добавлены новые разделы настроек: темы, уведомлений
