### ISSUE TITLE
Исправление внешнего вида профиля

### ISSUE THREAD

**Issue by AndreyKondakovGW** [AndreyKondakovGW/Project-Sbornik-Pervokursnika-#5]
Состоит из 3х пунктов, которые суммарно занимает полэкрана, но при этом зачем-то свёрнуты - убрать сворачивание, пусть листаются в крайнем случае, хотя уже и экранов то таких нет.

**Comment by DmitryiShvets** [comment]
Полностью изменен дизайн.
Растянул дропдан
